@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODNhYzA3ZS1iMDgwLTQxNmMtOGEwMS0xNDcwYjljZTQyNWYiLCJpYXQiOjE3NTc2ODc2OTJ9.EYcUAPG4lHOmGfnVAuNyIzF7Zo69fXQqP52c17sGxPk-Ru1vgrPLqV5UNuo4we7q9BZSvQ1QyU8NwlnMctz0vy3LNdnh6gCHAlg5Xew1d9q09RCwStOvS8SIQFSY1EedlDZzlEUs8fEPgzUsyBr_0rd6Q1fE9kjqjfdiPZ75P7WR4w6QbGfEWo6qCCR_3KArNXQEKWy02yc1vXXcXQlJyZv7D4ZmhZw0jWf855FFxqmgifd0wCdYVY8MNPUajLiJ0zDVN9X-KuqoA2xw8L2ZwbxRZQcWn83Tl3ARGIh9EeyYOfht1KOADqVIi-7HNU_bFUsyEgtlsQzTGLpYgp-0hg
